# kubectl apply -k kubernetes/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: techpix
resources:
  - namespace.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - monolith/configmap.yaml
  - monolith/secret.yaml
  - monolith/deployment.yaml
  - monolith/service.yaml
  - fraud-service/configmap.yaml
  - fraud-service/deployment.yaml
  - fraud-service/service.yaml
