apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techpix-qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ${TECHPIX_GIT_URL}
    targetRevision: main
    path: gitops/overlays/qa
  destination:
    server: https://kubernetes.default.svc
    namespace: techpix-qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
